disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - anonymous_argument_in_multiline_closure
included:
  - pair-programming
excluded:
  - Pods
  - pair-programming/ExcludedFolder
force_cast: error
force_try:
  severity: warning
line_length:
  warning: 120
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
type_body_length:
  - 300
  - 400
file_length:
  warning: 1000
  error: 1500
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone 
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" 
